/* Central TAGS bank and DATA for smart-pharma (demo) */
const TAGS = {
  "Симптомы": ["#боль","#больЖКТ","#больГорла","#головнаяБоль","#спазмы","#жар","#температура","#воспаление","#насморк","#чихание","#кашель","#заложенностьНоса","#одышка","#зуд","#жжение","#слабость","#усталость","#мигрень"],
  "Заболевания": ["#ОРВИ","#простуда","#ангина","#фарингит","#ларингит","#ринит","#аллергия","#бронхит","#астма","#грипп","#дисменорея","#холецистит","#язва","#рефлюкс","#геморрой","#авитаминоз","#микозы"],
  "Формы": ["#таблетки","#капсулы","#порошок","#сироп","#свечи","#капли","#спрей","#ампулы","#раствор","#инъекции","#гель","#мазь","#крем","#ингалятор","#дляРассасывания"],
  "Тип лечения": ["#СИМПТОМ","#патоген","#этиотроп","#витамины","#БАД"],
  "Фармакогруппы": ["#анальгетики","#НПВС","#спазмолитики","#антибиотики","#антигистаминные","#муколитики","#противокашлевые","#гормоны","#пробиотики"],
  "Служебные": ["#OTC","#Rx","#дети","#взрослые"]
};

const DATA = [
  {"id":0,"name":"Но-шпа","substance":"Дротаверин","form":"таблетки","symptoms":["боль в животе","спазмы","колики"],"disease":["дисменорея","холецистит"],"analogs":{"same_substance":["Спазмонет","Дротаверин-Тева"],"group_analogs":["Папаверин","Бускопан"],"other_forms":["ампулы"]},"prescription":false,"tags":["#больЖКТ","#спазмы","#таблетки","#СИМПТОМ","#OTC"],"img":"https://via.placeholder.com/400x220.png?text=No-shpa"},
  {"id":1,"name":"Парацетамол","substance":"Парацетамол","form":"таблетки","symptoms":["жар","головная боль","боль в теле"],"disease":["ОРВИ","простуда"],"analogs":{"same_substance":["Панадол","Эффералган"],"group_analogs":["Ибупрофен"],"other_forms":["сироп","свечи"]},"prescription":false,"tags":["#ОРВИ","#жар","#температура","#таблетки","#СИМПТОМ","#OTC"],"img":"https://via.placeholder.com/400x220.png?text=Paracetamol"},
  {"id":2,"name":"Ибупрофен","substance":"Ибупрофен","form":"таблетки","symptoms":["воспаление","жар","боль"],"disease":["артрит","ОРВИ"],"analogs":{"same_substance":["Нурофен"],"group_analogs":["Парацетамол"],"other_forms":["сироп","гель"]},"prescription":false,"tags":["#жар","#воспаление","#таблетки","#НПВС","#СИМПТОМ","#OTC"],"img":"https://via.placeholder.com/400x220.png?text=Ibuprofen"},
  {"id":3,"name":"Омепразол","substance":"Омепразол","form":"капсулы","symptoms":["изжога","боль в желудке"],"disease":["язва","рефлюкс"],"analogs":{"same_substance":["Омез","Омепразол-Акрихин"],"group_analogs":["Пантопразол","Рабепразол"],"other_forms":[]},"prescription":true,"tags":["#больЖКТ","#изжога","#капсулы","#патоген","#Rx"],"img":"https://via.placeholder.com/400x220.png?text=Omeprazole"},
  {"id":4,"name":"Амоксициллин","substance":"Амоксициллин","form":"капсулы","symptoms":["инфекция","воспаление"],"disease":["ангина","бронхит"],"analogs":{"same_substance":["Амоксиклав"],"group_analogs":["Азитромицин"],"other_forms":["суспензия"]},"prescription":true,"tags":["#инфекция","#капсулы","#антибиотики","#патоген","#Rx"],"img":"https://via.placeholder.com/400x220.png?text=Amoxicillin"},
  {"id":5,"name":"Азитромицин","substance":"Азитромицин","form":"таблетки","symptoms":["инфекция","кашель"],"disease":["ангина","бронхит"],"analogs":{"same_substance":["Сумамед"],"group_analogs":["Амоксициллин"],"other_forms":["суспензия"]},"prescription":true,"tags":["#инфекция","#кашель","#таблетки","#антибиотики","#Rx"],"img":"https://via.placeholder.com/400x220.png?text=Azithromycin"},
  {"id":6,"name":"Цетиризин","substance":"Цетиризин","form":"таблетки","symptoms":["чихание","зуд","насморк"],"disease":["аллергия","ринит"],"analogs":{"same_substance":["Зиртек"],"group_analogs":["Лоратадин"],"other_forms":["капли"]},"prescription":false,"tags":["#аллергия","#зуд","#таблетки","#антигистаминные","#OTC"],"img":"https://via.placeholder.com/400x220.png?text=Cetirizine"},
  {"id":7,"name":"Називин","substance":"Оксиметазолин","form":"капли","symptoms":["заложенность носа","насморк"],"disease":["ринит"],"analogs":{"same_substance":["Санорин"],"group_analogs":[],"other_forms":[]},"prescription":false,"tags":["#насморк","#капли","#СИМПТОМ","#OTC"],"img":"https://via.placeholder.com/400x220.png?text=Nazivin"},
  {"id":8,"name":"Фарингосепт","substance":"Амброксол/бензокаин","form":"таблетки для рассасывания","symptoms":["боль в горле","кашель"],"disease":["фарингит","ларингит"],"analogs":{"same_substance":["Стрепсилс"],"group_analogs":[],"other_forms":[]},"prescription":false,"tags":["#больГорла","#таблетки","#СИМПТОМ","#OTC"],"img":"https://via.placeholder.com/400x220.png?text=Faringosept"},
  {"id":9,"name":"Сальбутамол","substance":"Сальбутамол","form":"ингалятор","symptoms":["одышка","свистящее дыхание"],"disease":["бронхиальная астма"],"analogs":{"same_substance":["Вентолин"],"group_analogs":["Ипратропий"],"other_forms":[]},"prescription":true,"tags":["#астма","#ингалятор","#патоген","#Rx"],"img":"https://via.placeholder.com/400x220.png?text=Salbutamol"},
  {"id":10,"name":"Аспирин","substance":"Ацетилсалициловая кислота","form":"таблетки","symptoms":["боль","воспаление"],"disease":["мигрень"],"analogs":{"same_substance":[],"group_analogs":["Ибупрофен"],"other_forms":[]},"prescription":false,"tags":["#боль","#таблетки","#анальгетики","#OTC"],"img":"https://via.placeholder.com/400x220.png?text=Aspirin"},
  {"id":11,"name":"Витамин C","substance":"Аскорбиновая кислота","form":"таблетки","symptoms":["усталость","слабость"],"disease":["авитаминоз"],"analogs":{"same_substance":[],"group_analogs":[],"other_forms":["раствор"]},"prescription":false,"tags":["#витамины","#таблетки","#OTC"],"img":"https://via.placeholder.com/400x220.png?text=Vitamin+C"},
  {"id":12,"name":"Миконазол","substance":"Микомазол","form":"крем","symptoms":["зуд","грибковые поражения"],"disease":["микозы"],"analogs":{"same_substance":["Микозон"],"group_analogs":[],"other_forms":[]},"prescription":false,"tags":["#микоз","#крем","#СИМПТОМ","#OTC"],"img":"https://via.placeholder.com/400x220.png?text=Myconazole"},
  {"id":13,"name":"Кеторолак","substance":"Кеторолак","form":"таблетки/инъекции","symptoms":["сильная боль"],"disease":["болевые синдромы"],"analogs":{"same_substance":["Кетанов"],"group_analogs":[],"other_forms":["ампулы"]},"prescription":true,"tags":["#боль","#инъекции","#НПВС","#Rx"],"img":"https://via.placeholder.com/400x220.png?text=Ketorolac"},
  {"id":14,"name":"Проктозан","substance":"Хлорид бензалкония/преднизолон/оксид цинка","form":"мазь","symptoms":["жжение","зуд"],"disease":["геморрой"],"analogs":{"same_substance":["Проктоседил"],"group_analogs":[],"other_forms":[]},"prescription":false,"tags":["#геморрой","#мазь","#СИМПТОМ","#OTC"],"img":"https://via.placeholder.com/400x220.png?text=Proctosan"},
  {"id":15,"name":"Назонекс","substance":"Мометазон","form":"спрей","symptoms":["аллергия","насморк"],"disease":["ринит"],"analogs":{"same_substance":["Мометазон"],"group_analogs":["Флутиказон"],"other_forms":[]},"prescription":true,"tags":["#аллергия","#спрей","#патоген","#Rx"],"img":"https://via.placeholder.com/400x220.png?text=Nasonex"},
  {"id":16,"name":"Глюкоза 5%","substance":"Глюкоза","form":"раствор для инфузий","symptoms":["обезвоживание"],"disease":["обезвоживание"],"analogs":{"same_substance":[],"group_analogs":[],"other_forms":[]},"prescription":false,"tags":["#обезвоживание","#раствор","#OTC"],"img":"https://via.placeholder.com/400x220.png?text=Glucose"},
  {"id":17,"name":"Дротаверин (ампулы)","substance":"Дротаверин","form":"ампулы","symptoms":["спазмы"],"disease":["колики"],"analogs":{"same_substance":["Но-шпа"],"group_analogs":["Папаверин"],"other_forms":["таблетки"]},"prescription":false,"tags":["#спазмы","#ампулы","#СИМПТОМ","#OTC"],"img":"https://via.placeholder.com/400x220.png?text=DrotaverineAmp"},
  {"id":18,"name":"Лоратадин","substance":"Лоратадин","form":"таблетки","symptoms":["зуд","насморк"],"disease":["аллергия"],"analogs":{"same_substance":["Кларитин"],"group_analogs":["Цетиризин"],"other_forms":[]},"prescription":false,"tags":["#аллергия","#таблетки","#антигистаминные","#OTC"],"img":"https://via.placeholder.com/400x220.png?text=Loratadine"},
  {"id":19,"name":"Пантопразол","substance":"Пантопразол","form":"таблетки","symptoms":["изжога","боль в желудке"],"disease":["рефлюкс"],"analogs":{"same_substance":["Пантопразол"],"group_analogs":["Омепразол"],"other_forms":[]},"prescription":true,"tags":["#больЖКТ","#капсулы","#патоген","#Rx"],"img":"https://via.placeholder.com/400x220.png?text=Pantoprazole"}
];
